# Generated by Django 5.1.2 on 2024-12-29 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEmpleado', models.CharField(max_length=255)),
                ('UsuarioEmpleado', models.CharField(max_length=100, unique=True)),
                ('ContrasenaEmpleado', models.CharField(max_length=128)),
                ('CorreoEmpleado', models.EmailField(max_length=254, unique=True)),
                ('NumeroEmpleado', models.CharField(max_length=15)),
                ('Activo', models.BooleanField(default=False)),
                ('Latitud', models.FloatField(blank=True, null=True)),
                ('Longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=255)),
                ('RFCEmpresa', models.CharField(max_length=13, unique=True)),
                ('NumeroEmpresa', models.CharField(max_length=15)),
                ('CorreoEmpresa', models.EmailField(max_length=254, unique=True)),
                ('ContrasenaEmpresa', models.CharField(max_length=128)),
                ('TituloEmpresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('empresa', 'Empresa'), ('empleado', 'Empleado')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('activa', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='EmpresaEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.empresa'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_empresa', models.BooleanField(default=False)),
                ('is_empleado', models.BooleanField(default=False)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
