# Generated by Django 5.1.2 on 2024-12-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='CorreoEmpleado',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='UsuarioEmpleado',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
